[package]
name = "OutlookClient"
version = "0.2.0"
description = "An unofficial Linux desktop wrapper for Microsoft Outlook built with Tauri."
authors = ["maxiking445"]
license = "GPL 3.0"
repository = "https://github.com/maxiking445/outlook-for-linux"
edition = "2021"
rust-version = "1.90"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
serde_json = "1.0"
tauri-plugin-opener = "2.7.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.1", features = ["tray-icon", "devtools"] }
tauri-plugin-log = "2.10.0"
tauri-plugin-notification = "2.5.1"
futures = "0.3"
tauri-plugin-dialog = "2.8.1"
base64 = "0.23.0"
tauri-plugin-single-instance = "2.4.2"
tauri-plugin-store = "2.4.3"

[target.'cfg(target_os = "linux")'.dependencies]
notify-rust = "4.11.7"
