name: maxiking445-outlook-for-linux
version: '1.0.0'
summary: An unofficial Linux desktop wrapper for Microsoft Outlook built with Tauri.
description: |
  An unofficial Linux desktop wrapper for Microsoft Outlook built with Tauri.
contact: maxiking445@proton.me
license: MIT
issues: https://github.com/maxiking445/outlook-for-linux/issues
source-code: https://github.com/maxiking445/outlook-for-linux
website: https://github.com/maxiking445/outlook-for-linux
grade: stable
confinement: strict

base: core22

apps:
  outlook-for-linux:
    command: OutlookClient
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - unity7
      - network
      - audio-playback
      - home

parts:
  outlook-for-linux:
    plugin: dump
    source: client/src-tauri/target/release
    stage-packages:
      - libwebkit2gtk-4.0-37
